import SwiftUI

struct BagView: View {
    @EnvironmentObject private var store: AppStore
    var body: some View {
        List {
            Section { ForEach(store.persistentBag) { item in HStack { VStack(alignment: .leading) { Text(item.product.name).bold(); Text(item.product.brand).font(.caption).foregroundStyle(.secondary) }; Spacer(); Text("×\(item.quantity)") } } } header: { Text("Saved bag") }
            if store.persistentBag.isEmpty { ContentUnavailableView("Your bag is empty", systemImage: "bag", description: Text("Add a product from the Decide tab.")) }
            Section { Button("Optimize demo bag") { Task { await store.optimize() } } }
        }.navigationTitle("My Bag").refreshable { await store.loadMemory() }
    }
}

struct PlansView: View {
    var body: some View {
        ScrollView { VStack(spacing: 16) {
            BrandHeader(eyebrow: "Consumer + Coach", title: "Plans", subtitle: "Meal and workout plans generated by the shared FastAPI intelligence layer.")
            NavigationLink { PlaceholderPlanView(title: "Meal planner", icon: "fork.knife") } label: { PlanCard(title: "Build meal plan", subtitle: "Use goals, diet, allergies, and calorie target.", icon: "fork.knife") }
            NavigationLink { PlaceholderPlanView(title: "Workout planner", icon: "figure.strengthtraining.traditional") } label: { PlanCard(title: "Build workout plan", subtitle: "Create a weekly split from goal and equipment.", icon: "figure.strengthtraining.traditional") }
        }.padding() }.background(Color.guiltlessCanvas).navigationTitle("Plans")
    }
}
private struct PlanCard: View { let title: String; let subtitle: String; let icon: String; var body: some View { HStack { Image(systemName: icon).font(.title).frame(width: 48); VStack(alignment: .leading) { Text(title).bold(); Text(subtitle).font(.caption).foregroundStyle(.secondary) }; Spacer(); Image(systemName: "chevron.right") }.foregroundStyle(Color.guiltlessGreen).cardStyle() } }
private struct PlaceholderPlanView: View { let title: String; let icon: String; var body: some View { ContentUnavailableView(title, systemImage: icon, description: Text("The API is ready; the detailed native form is the next screen to add.")) } }

struct ProfileView: View {
    @EnvironmentObject private var store: AppStore
    @State private var goal = "balanced nutrition"; @State private var diet = "no restriction"; @State private var allergies = ""; @State private var preferredStore = "Instacart"; @State private var calories = 2200
    var body: some View {
        Form {
            Section("Planning") { NavigationLink("Meal and workout plans") { PlansView() } }
            Section("Memory") { TextField("Goal", text: $goal); TextField("Diet", text: $diet); TextField("Allergies, comma separated", text: $allergies); TextField("Preferred store", text: $preferredStore); Stepper("Calorie target: \(calories)", value: $calories, in: 800...6000, step: 50) }
            Section { Button("Save profile") { Task { await store.saveProfile(goal: goal, diet: diet, allergies: allergies, store: preferredStore, calories: calories) } }.buttonStyle(GuiltlessButtonStyle()) }
            Section("Connection") { LabeledContent("API", value: APIClient.baseURL.absoluteString); LabeledContent("User", value: store.userID) }
        }.navigationTitle("Profile").onAppear { if let profile = store.profile { goal = profile.goal; diet = profile.diet; allergies = profile.allergies.joined(separator: ", "); preferredStore = profile.preferredStore; calories = profile.calorieTarget } }
    }
}
